#!/bin/bash

#SBATCH -N 4 --cpus-per-task=12
#SBATCH --time=02:30:00
#SBATCH --output=out_inter/Messung1.out

srun ./messreihe_inter.sh 4 &
srun ./messreihe_inter.sh 5 &
srun ./messreihe_inter.sh 6 &
srun ./messreihe_inter.sh 7
