#!/bin/bash

#SBATCH -N 4 --cpus-per-task=12
#SBATCH --time=01:30:00
#SBATCH --output=out/Messung1.out

srun ./messreihe_threads.sh 4 &
srun ./messreihe_threads.sh 5 &
srun ./messreihe_threads.sh 6 &
srun ./messreihe_threads.sh 3
