#!/bin/bash

#SBATCH --cpus-per-task=12
#SBATCH --time=01:30:00
#SBATCH --output=out/Messung1.out

srun ./messreihe_threads.sh 1
srun ./messreihe_threads.sh 2
srun ./messreihe_threads.sh 3 
srun ./messreihe_threads.sh 4
